name: Main Deploy

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Digital House
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: bash pfk-api/deploy.sh
          username: root
          host: ${{ secrets.HOST }}
          privateKey: ${{ secrets.PRIVATE_KEY }}
