name: Main Deploy

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - uses: kielabokkie/ssh-key-and-known-hosts-action@v1.2.0
        with:
          ssh-private-key: ${{secrets.PRIVATE_KEY_MAIN}}
            # Hostname or IP to add to the known hosts file
          ssh-host: ${{secrets.HOST}}
            # Port for key-scanning the server
          ssh-port: 22
