name: Main Deploy

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - uses: cross-the-world/ssh-pipeline@master
        with:
            host: ${{ secrets.HOST }}
            pass: ${{ secrets.PASSPHRASE_NAME }}
            port: 22
            connect_timeout: 10s
            script: |
              bash pfk-api/test.sh
